---
- hosts: all
  gather_facts: true

  vars:
    remote_path: "{{ ansible_env.HOME }}/performance-testing"
    duration: "{{ artillery_duration | default(180) | int }}"
    arrival_rate: "{{ artillery_arrival_rate | default(10) | int }}"
    number_of_hosts: "{{ groups['all'] | length | int }}"
    rps: "{{ (arrival_rate | int) * number_of_hosts | int }}"
    hostname: "{{ ansible_ec2_public_hostname }}"
    json_report: "{{ remote_path }}/{{ hostname }}-report-{{ rps }}-rps.json"
    html_report: "{{ remote_path }}/{{ hostname }}-report-{{ rps }}-rps.html"

  tasks:

    - name: gather EC2 instance metadata
      action: ec2_metadata_facts

    - name: update the urls list path
      replace:
        path: "{{ remote_path }}/artillery-web.yml"
        regexp: 'duration:(\s+.*)'
        replace: 'duration: {{ duration }}'
        backup: yes

    - name: update the urls list path
      replace:
        path: "{{ remote_path }}/artillery-web.yml"
        regexp: 'arrivalRate:(\s+.*)'
        replace: 'arrivalRate: {{ arrival_rate }}'
        backup: yes

    - name: update the urls list path
      replace:
        path: "{{ remote_path }}/artillery-mobile.yml"
        regexp: 'duration:(\s+.*)'
        replace: 'duration: {{ duration }}'
        backup: yes

    - name: update the urls list path
      replace:
        path: "{{ remote_path }}/artillery-mobile.yml"
        regexp: 'arrivalRate:(\s+.*)'
        replace: 'arrivalRate: {{ arrival_rate }}'
        backup: yes

    - name: ensure the remote json report does not exist
      file:
        path: "{{ json_report }}"
        state: absent

    - name: ensure the remote html report does not exist
      file:
        path: "{{ html_report }}"
        state: absent

    - name: executes web performance test
      command: 'artillery run -o {{ json_report }} "{{ remote_path }}/artillery-web.yml"'

    - name: create html report
      command: 'artillery report {{ json_report }} -o {{ html_report }}'

    - name: fetch the json reports locally
      fetch:
        src: "{{ json_report }}"
        dest: "./results/"
        flat: yes

    - name: fetch the html reports locally
      fetch:
        src: "{{ html_report }}"
        dest: "./results/"
        flat: yes
